server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/authdb}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

jwt:
  secret: ${JWT_SECRET:MiSuperSecretKeyParaDesarrolloLocal}

springdoc:
  swagger-ui:
    path: /swagger-ui.html