services:

  auth-service:
    image: auth-service:latest
    ports:
      - "8081:8081"

  user-service:
    image: user-service:latest
    ports:
      - "8082:8082"

  frontend:
    image: frontend-auth-ui:latest
    ports:
      - "80:80"